In [17]:
# load the libraries
import numpy as np
import pandas as pd
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization, Conv2D, Flatten, Dense

In [18]:
# load the dataset
dataset = loadtxt(fname="survey lung cancer.csv", delimiter=',', skiprows=1)

In [20]:
# split data into input and output variables
feature_vector = dataset[:, 0:15]
target_vector = dataset[:, 15]
print(feature_vector)
print(target_vector)

[[ 0. 69.  1. ...  2.  2.  2.]
 [ 0. 74.  2. ...  2.  2.  2.]
 [ 1. 59.  1. ...  2.  1.  2.]
 ...
 [ 1. 38.  2. ...  2.  1.  2.]
 [ 0. 26.  2. ...  1.  1.  1.]
 [ 0. 61.  2. ...  2.  1.  1.]]
[1. 1. 2. ... 1. 2. 2.]
55394


In [21]:
# reshape the data to simulate a greyscale image
tmp = np.array(feature_vector)
tmp = tmp.reshape(-1, 2, 4)
feature_vector = pd.DataFrame(sum(map(list, tmp), []))
tmp = []
for i,g in X.groupby(np.arange(len(feature_vector)) // 2):
    tmp.append(g)
tmp = np.array([i.to_numpy() for i in tmp])
feature_vector = tmp.reshape(55394, 2, 4, 1)#error

ValueError: cannot reshape array of size 830910 into shape (2,4)

In [13]:
# define the keras model
model = Sequential()
model.add(Conv2D(1, activation="relu", kernel_size=2, input_shape=(2, 4, 1)))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dense(1, input_shape=(2, 4, 1), activation='sigmoid'))

In [14]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
# fit the keras model on the dataset
model.fit(X, Y, epochs=20, batch_size=0)

ValueError: Data cardinality is ambiguous:
  x sizes: 110788
  y sizes: 55394
Make sure all arrays contain the same number of samples.

In [16]:
# evaluate the keras model
accuracy = model.evaluate(X, Y)
print("Accuracy: %.2f" % (accuracy*100))

ValueError: Data cardinality is ambiguous:
  x sizes: 110788
  y sizes: 55394
Make sure all arrays contain the same number of samples.