# Lung Cancer Analysis & Prediction using CovNet

In [23]:
# load the libraries
import numpy as np
import pandas as pd
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization, Conv2D, Flatten, Dense

In [24]:
# load the dataset
dataset = loadtxt(fname="survey lung cancer.csv", delimiter=',', skiprows=1)

In [25]:
# split data into input and output variables
feature_vector = dataset[:, 0:15]
target_vector = dataset[:, 15]
print(feature_vector)
print(target_vector)

[[ 0. 69.  1. ...  2.  2.  2.]
 [ 0. 74.  2. ...  2.  2.  2.]
 [ 1. 59.  1. ...  2.  1.  2.]
 ...
 [ 1. 38.  2. ...  2.  1.  2.]
 [ 0. 26.  2. ...  1.  1.  1.]
 [ 0. 61.  2. ...  2.  1.  1.]]
[1. 1. 2. ... 1. 2. 2.]


In [32]:
# reshape the data to simulate a greyscale image
tmp = np.array(feature_vector)
tmp = tmp.reshape(-1, 3, 5)
feature_vector = pd.DataFrame(sum(map(list, tmp), []))
tmp = []
for i,g in feature_vector.groupby(np.arange(len(feature_vector)) // 2):
    tmp.append(g)
tmp = np.array([i.to_numpy() for i in tmp])
feature_vector = tmp.reshape(55394, 3, 5, 1)#error

In [33]:
# define the keras model
model = Sequential()
model.add(Conv2D(1, activation="relu", kernel_size=2, input_shape=(3, 5, 1)))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dense(1, input_shape=(3, 5, 1), activation='sigmoid'))

In [34]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
# fit the keras model on the dataset
model.fit(feature_vector, target_vector, epochs=20, batch_size=0)

Epoch 1/20
1732/1732 [==============================] - 4s 2ms/step - loss: -13.2356 - accuracy: 0.5039
Epoch 2/20
1732/1732 [==============================] - 3s 2ms/step - loss: -80.1402 - accuracy: 0.5039
Epoch 3/20
1732/1732 [==============================] - 3s 2ms/step - loss: -193.9922 - accuracy: 0.5039
Epoch 4/20
1732/1732 [==============================] - 3s 2ms/step - loss: -345.9562 - accuracy: 0.5039
Epoch 5/20
1732/1732 [==============================] - 3s 2ms/step - loss: -533.4173 - accuracy: 0.5039
Epoch 6/20
1732/1732 [==============================] - 3s 2ms/step - loss: -755.4995 - accuracy: 0.5039
Epoch 7/20
1732/1732 [==============================] - 3s 2ms/step - loss: -1011.3184 - accuracy: 0.5039
Epoch 8/20
1732/1732 [==============================] - 3s 2ms/step - loss: -1301.2986 - accuracy: 0.5039
Epoch 9/20
1732/1732 [==============================] - 3s 2ms/step - loss: -1624.7628 - accuracy: 0.5039
Epoch 10/20
1732/1732 [==============================]

In [37]:
# evaluate the keras model
accuracy = model.evaluate(feature_vector, target_vector)
print("Accuracy: " + str(accuracy*100))

1732/1732 [==============================] - 2s 1ms/step - loss: -7693.6372 - accuracy: 0.5039
Accuracy: [-7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0.503899335861206, -7693.63720703125, 0